### PR TITLE
Updates19 1

### PR DESCRIPTION
**Pull request by Meivenkatkumar**
updating events and workshops page along with main home page background picture

### CODE REVIEW

**Comment by Meivenkatkumar** [comment]
not sure of where to place the second background image. 
review required for dr.deendayal`s image ratio

**Comment by Meivenkatkumar** [comment]
updating events timing 
uploading member`s pic

**Comment by Meivenkatkumar** [comment]
few member`s pic are yet to be uploaded

**Comment by Meivenkatkumar** [comment]
Moments_19

**Comment by Meivenkatkumar** [comment]
Sathwik`s & asish`s pics need to be included

**Comment by kumaran-14** [comment]
Learn to amend commits. Existing commits can be amended before pushing to include updates and corrections.

**Pull request merged**
